version: '3'
services:
  httpmole:
    image: httpmole
    volumes:
        - $PWD/response.json:/httpmole/response.json
    command: ["-response-file", "/httpmole/response.json"]
    ports:
        - "8081:8081"
    expose:
        - 8081
